import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import Breadcrumb from "@/components/Breadcrumb";
import "../../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Project Manager - Company",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="sticky top-0 z-50">
          <Navbar />
          <Breadcrumb />
        </div>
        <div className="bg-gray-200 h-screen px-8">{children}</div>
      </body>
    </html>
  );
}
